### ISSUE TITLE
Decide which design are going to implement

### ISSUE THREAD

**Issue by DevPacoLuna** [DevPacoLuna/Notus-Ecommerce#1]

**Comment by LuisRococo** [comment]
Options:
- https://www.templatemonster.com/shopify-themes/toolgard-mega-tools-store-shopify-2-0-responsive-theme-332144.html#thumbnail-5
- https://www.templatemonster.com/woocommerce-themes/electro-mega-shop-multipurpose-elementor-woocommerce-store-198900.html
- https://www.templatemonster.com/woocommerce-themes/matjar-multipurpose-woocommerce-wordpress-theme-323252.html

**Comment by LuisRococo** [comment]
We decided to base our design on this page's design:
https://www.templatemonster.com/woocommerce-themes/electro-mega-shop-multipurpose-elementor-woocommerce-store-198900.html
